### PR TITLE
Included NEW_SAFE_RANGE in Keychron K series enums

### PR DESCRIPTION
**Pull request by campbellhennessy**
Following guidance from QMK docs (https://docs.qmk.fm/#/configurator_default_keymaps?id=custom-keycodes) included NEW_SAFE_RANGE at the end of the enum defining vendor level custom keycodes for K-series boards.  This ensures that when users define their own keymaps, if they start at NEW_SAFE_RANGE, that their codes will not collide with vendor codes.  This is especially true if the vendor adds or removes codes in future updates.

In each K-series board header I added a final entry into the custom keycode enum called NEW_SAFE_RANGE.

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [X] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* Users defining custom keymaps will easily run into conflicts with the keycodes defined by the vendor.

## Checklist

- [X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by danielbibit** [comment]
Maybe this info could also be added to the documentation, I spent a few minutes today debbuging one macro because of this.

**Comment by campbellhennessy** [comment]
Just wondering if there is anything more that you need on my end to consider this pull request

**Comment by stuartsoft** [comment]
@campbellhennessy I think the Keychron staff might be on holiday for the new year rn.

**Comment by stuartsoft** [comment]
@lalalademaxiya1 @lokher when possible, can we get feedback on this PR?

**Pull request merged**
