### PR TITLE
Update rules.mk

### PR DESCRIPTION
**Pull request by sexyboya**
## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by sexyboya** [comment]
yorosiku

**Comment by lokher** [comment]
mouse key is already enable in info.json:
https://github.com/Keychron/qmk_firmware/blob/fd70215008ef2fccf5acc0aad57499d7e0ceef86/keyboards/keychron/q6_max/info.json#L14

**Comment by sexyboya** [comment]
Thank you very much.
But no matter how I try, I cannot enter mouse clicks into the Via macro.
Is there another way to do this?
I will attach the image to this email.

**Comment by lokher** [comment]
> Thank you very much. But no matter how I try, I cannot enter mouse clicks into the Via macro. Is there another way to do this? I will attach the image to this email.

Mouse click is not supported in VIA, you have to switch to build the macro with QMK:
https://github.com/qmk/qmk_firmware/blob/master/docs/feature_macros.md

**Comment by PeterMortensen** [comment]
> I cannot enter mouse clicks into the Via macro. Is there another way to do this?

It *is* possible to use mouse clicks in a Via macro by applying ***[a hack](https://pmortensen.eu/world2/2024/02/26/a-hack-to-use-mouse-actions-in-via-macros/)***.

**Pull request closed without merging**
