### PR TITLE
Q6 Pro Openrgb + Via support

### PR DESCRIPTION
**Pull request by Phara0h**
## Description

Added Openrgb support that also maintains Via support for Q6 Pro (work can easily be copied for the others). You can toggle via <--> opengrb mode with fn+q

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

*  https://github.com/Keychron/qmk_firmware/issues/176

## Checklist

- [ ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Comment by lokher** [comment]
Thanks for contributing, but we have no plan to add OpenRGB in this branch, but we will consider adding a new branch for it later.

**Comment by qiangqiang101** [comment]
can you also make one for V6?

**Comment by Sasuchisama** [comment]
@Phara0h You put the switch-key on FN +"o". Work with OpenRGB like expected. Thank you :)

**Comment by NovaViper** [comment]
🤔 I wonder how hard it would be to port this over to the K8 Pro

**Comment by PeterMortensen** [comment]
Somewhat related: *[XAP (née QMK API) discovery and scoping #11567](https://github.com/qmk/qmk_firmware/issues/11567)*. Sub title: *"QMK API, AKA Via + OpenRGB + other [raw HID](https://www.pjrc.com/teensy/rawhid.html) all bundled into one"*

E.g., [PR #10961](https://github.com/qmk/qmk_firmware/pull/10961): *"Implement the OpenRGB protocol for RGB matrix keyboards"*

**Pull request closed without merging**
